// Copyright 2026 The Gitea Authors. All rights reserved.
// SPDX-License-Identifier: MIT

// Code generated by tools/delivery-generate.go. DO NOT EDIT.
//
// The request layer is generated from the API's operation set, the same set the published
// OpenAPI document is generated from, so a call that no longer matches the contract fails
// the build rather than at runtime (K2).

package main

// Commands is every command the CLI serves, one per documented endpoint (K3, K7).
var Commands = []Command{
	{
		Name:        "audit",
		OperationID: "listAudit",
		Method:      "GET",
		Path:        "/audit",
		Summary:     "List delivery audit events across every repository the caller can see",
		PathParams:  nil,
		QueryParams: []string{"actor_id", "actor_id[gt]", "actor_id[gte]", "actor_id[in]", "actor_id[lt]", "actor_id[lte]", "actor_id[ne]", "actor_login", "actor_login[contains]", "actor_login[in]", "actor_login[ne]", "cursor", "environment", "environment[contains]", "environment[in]", "environment[ne]", "event", "event[contains]", "event[in]", "event[ne]", "id", "id[gt]", "id[gte]", "id[in]", "id[lt]", "id[lte]", "id[ne]", "limit", "occurred_unix", "occurred_unix[gt]", "occurred_unix[gte]", "occurred_unix[in]", "occurred_unix[lt]", "occurred_unix[lte]", "occurred_unix[ne]", "order", "q", "release_tag", "release_tag[contains]", "release_tag[in]", "release_tag[ne]", "repo_id", "repo_id[gt]", "repo_id[gte]", "repo_id[in]", "repo_id[lt]", "repo_id[lte]", "repo_id[ne]", "run_id", "run_id[gt]", "run_id[gte]", "run_id[in]", "run_id[lt]", "run_id[lte]", "run_id[ne]", "sort_by", "source", "source[contains]", "source[in]", "source[ne]"},
		Columns:     []string{"actor_id", "actor_login", "environment", "event", "id", "occurred_unix", "release_tag", "repo_id", "run_id", "source"},
		IsList:      true,
	},
	{
		Name:        "deployments",
		OperationID: "listDeployments",
		Method:      "GET",
		Path:        "/deployments",
		Summary:     "List deployments across every repository the caller can see",
		PathParams:  nil,
		QueryParams: []string{"branch", "branch[contains]", "branch[in]", "branch[ne]", "created_unix", "created_unix[gt]", "created_unix[gte]", "created_unix[in]", "created_unix[lt]", "created_unix[lte]", "created_unix[ne]", "cursor", "environment", "environment[contains]", "environment[in]", "environment[ne]", "expand", "id", "id[gt]", "id[gte]", "id[in]", "id[lt]", "id[lte]", "id[ne]", "limit", "order", "q", "release_tag", "release_tag[contains]", "release_tag[in]", "release_tag[ne]", "repo_id", "repo_id[gt]", "repo_id[gte]", "repo_id[in]", "repo_id[lt]", "repo_id[lte]", "repo_id[ne]", "run_id", "run_id[gt]", "run_id[gte]", "run_id[in]", "run_id[lt]", "run_id[lte]", "run_id[ne]", "sha", "sha[contains]", "sha[in]", "sha[ne]", "sort_by", "status", "status[contains]", "status[in]", "status[ne]"},
		Columns:     []string{"created_unix", "environment", "id", "release_tag", "repo_id", "run_id", "status"},
		IsList:      true,
	},
	{
		Name:        "environments",
		OperationID: "listEnvironments",
		Method:      "GET",
		Path:        "/environments",
		Summary:     "List environments across every repository the caller can see",
		PathParams:  nil,
		QueryParams: []string{"approval_policy", "approval_policy[contains]", "approval_policy[in]", "approval_policy[ne]", "created_unix", "created_unix[gt]", "created_unix[gte]", "created_unix[in]", "created_unix[lt]", "created_unix[lte]", "created_unix[ne]", "id", "id[gt]", "id[gte]", "id[in]", "id[lt]", "id[lte]", "id[ne]", "limit", "name", "name[contains]", "name[in]", "name[ne]", "order", "page", "q", "repo_id", "repo_id[gt]", "repo_id[gte]", "repo_id[in]", "repo_id[lt]", "repo_id[lte]", "repo_id[ne]", "required_approvals", "required_approvals[gt]", "required_approvals[gte]", "required_approvals[in]", "required_approvals[lt]", "required_approvals[lte]", "required_approvals[ne]", "sort_by", "sort_order", "sort_order[gt]", "sort_order[gte]", "sort_order[in]", "sort_order[lt]", "sort_order[lte]", "sort_order[ne]", "updated_unix", "updated_unix[gt]", "updated_unix[gte]", "updated_unix[in]", "updated_unix[lt]", "updated_unix[lte]", "updated_unix[ne]"},
		Columns:     []string{"approval_policy", "id", "name", "repo_id", "required_approvals", "sort_order"},
		IsList:      true,
	},
	{
		Name:        "grid",
		OperationID: "getGrid",
		Method:      "GET",
		Path:        "/grid",
		Summary:     "The release × environment grid",
		PathParams:  nil,
		QueryParams: []string{"environment", "limit", "page", "release_tag", "repo_id"},
		Columns:     []string{"cells", "release_tag", "repo_full_name", "repo_id"},
		IsList:      true,
	},
	{
		Name:        "releases",
		OperationID: "listReleases",
		Method:      "GET",
		Path:        "/repos/{owner}/{repo}/releases",
		Summary:     "List a repository's releases, the rows of the grid",
		PathParams:  []string{"owner", "repo"},
		QueryParams: []string{"created_unix", "created_unix[gt]", "created_unix[gte]", "created_unix[in]", "created_unix[lt]", "created_unix[lte]", "created_unix[ne]", "expand", "id", "id[gt]", "id[gte]", "id[in]", "id[lt]", "id[lte]", "id[ne]", "is_prerelease", "is_prerelease[ne]", "limit", "order", "page", "q", "repo_id", "repo_id[gt]", "repo_id[gte]", "repo_id[in]", "repo_id[lt]", "repo_id[lte]", "repo_id[ne]", "sort_by", "tag_name", "tag_name[contains]", "tag_name[in]", "tag_name[ne]"},
		Columns:     []string{"created_unix", "id", "repo_id", "tag_name", "target", "url"},
		IsList:      true,
	},
	{
		Name:        "repo-environment",
		OperationID: "getRepoEnvironment",
		Method:      "GET",
		Path:        "/repos/{owner}/{repo}/environments/{name}",
		Summary:     "Read one environment",
		PathParams:  []string{"owner", "repo", "name"},
		QueryParams: nil,
		Columns:     []string{"approval_policy", "id", "name", "repo_id", "required_approvals", "sort_order"},
		IsList:      false,
	},
	{
		Name:        "repo-environment-secrets",
		OperationID: "listRepoEnvironmentSecrets",
		Method:      "GET",
		Path:        "/repos/{owner}/{repo}/environments/{name}/secrets",
		Summary:     "List the secret NAMES scoped to one environment",
		PathParams:  []string{"owner", "repo", "name"},
		QueryParams: []string{"environment", "environment[contains]", "environment[in]", "environment[ne]", "limit", "name", "name[contains]", "name[in]", "name[ne]", "order", "page", "q", "repo_id", "repo_id[gt]", "repo_id[gte]", "repo_id[in]", "repo_id[lt]", "repo_id[lte]", "repo_id[ne]", "sort_by"},
		Columns:     []string{"environment", "name", "repo_id", "scoped"},
		IsList:      true,
	},
	{
		Name:        "repo-environments",
		OperationID: "listRepoEnvironments",
		Method:      "GET",
		Path:        "/repos/{owner}/{repo}/environments",
		Summary:     "List one repository's environments",
		PathParams:  []string{"owner", "repo"},
		QueryParams: []string{"approval_policy", "approval_policy[contains]", "approval_policy[in]", "approval_policy[ne]", "created_unix", "created_unix[gt]", "created_unix[gte]", "created_unix[in]", "created_unix[lt]", "created_unix[lte]", "created_unix[ne]", "id", "id[gt]", "id[gte]", "id[in]", "id[lt]", "id[lte]", "id[ne]", "limit", "name", "name[contains]", "name[in]", "name[ne]", "order", "page", "q", "repo_id", "repo_id[gt]", "repo_id[gte]", "repo_id[in]", "repo_id[lt]", "repo_id[lte]", "repo_id[ne]", "required_approvals", "required_approvals[gt]", "required_approvals[gte]", "required_approvals[in]", "required_approvals[lt]", "required_approvals[lte]", "required_approvals[ne]", "sort_by", "sort_order", "sort_order[gt]", "sort_order[gte]", "sort_order[in]", "sort_order[lt]", "sort_order[lte]", "sort_order[ne]", "updated_unix", "updated_unix[gt]", "updated_unix[gte]", "updated_unix[in]", "updated_unix[lt]", "updated_unix[lte]", "updated_unix[ne]"},
		Columns:     []string{"approval_policy", "id", "name", "repo_id", "required_approvals", "sort_order"},
		IsList:      true,
	},
	{
		Name:        "repos",
		OperationID: "listRepos",
		Method:      "GET",
		Path:        "/repos",
		Summary:     "List the repositories the caller can see delivery data for",
		PathParams:  nil,
		QueryParams: []string{"id", "id[gt]", "id[gte]", "id[in]", "id[lt]", "id[lte]", "id[ne]", "is_archived", "is_archived[ne]", "limit", "name", "name[contains]", "name[in]", "name[ne]", "order", "owner_name", "owner_name[contains]", "owner_name[in]", "owner_name[ne]", "page", "q", "sort_by"},
		Columns:     []string{"full_name", "id", "name", "owner"},
		IsList:      true,
	},
}
