// Copyright 2026 The Gitea Authors. All rights reserved.
// SPDX-License-Identifier: MIT

// Code generated by tools/delivery-generate.go. DO NOT EDIT.
//
// The request layer is generated from the API's operation set, the same set the published
// OpenAPI document is generated from, so a call that no longer matches the contract fails
// the build rather than at runtime (K2).

package main

// Commands is every command the CLI serves, one per documented endpoint (K3, K7).
var Commands = []Command{
	{
		Name:        "environments",
		OperationID: "listEnvironments",
		Method:      "GET",
		Path:        "/environments",
		Summary:     "List environments across every repository the caller can see",
		PathParams:  nil,
		QueryParams: []string{"approval_policy", "approval_policy[contains]", "approval_policy[in]", "approval_policy[ne]", "created_unix", "created_unix[gt]", "created_unix[gte]", "created_unix[in]", "created_unix[lt]", "created_unix[lte]", "created_unix[ne]", "id", "id[gt]", "id[gte]", "id[in]", "id[lt]", "id[lte]", "id[ne]", "limit", "name", "name[contains]", "name[in]", "name[ne]", "order", "page", "q", "repo_id", "repo_id[gt]", "repo_id[gte]", "repo_id[in]", "repo_id[lt]", "repo_id[lte]", "repo_id[ne]", "required_approvals", "required_approvals[gt]", "required_approvals[gte]", "required_approvals[in]", "required_approvals[lt]", "required_approvals[lte]", "required_approvals[ne]", "sort_by", "sort_order", "sort_order[gt]", "sort_order[gte]", "sort_order[in]", "sort_order[lt]", "sort_order[lte]", "sort_order[ne]", "updated_unix", "updated_unix[gt]", "updated_unix[gte]", "updated_unix[in]", "updated_unix[lt]", "updated_unix[lte]", "updated_unix[ne]"},
		Columns:     []string{"approval_policy", "id", "name", "repo_id", "required_approvals", "sort_order"},
		IsList:      true,
	},
	{
		Name:        "repo-environment",
		OperationID: "getRepoEnvironment",
		Method:      "GET",
		Path:        "/repos/{owner}/{repo}/environments/{name}",
		Summary:     "Read one environment",
		PathParams:  []string{"owner", "repo", "name"},
		QueryParams: nil,
		Columns:     []string{"approval_policy", "id", "name", "repo_id", "required_approvals", "sort_order"},
		IsList:      false,
	},
	{
		Name:        "repo-environment-secrets",
		OperationID: "listRepoEnvironmentSecrets",
		Method:      "GET",
		Path:        "/repos/{owner}/{repo}/environments/{name}/secrets",
		Summary:     "List the secret NAMES scoped to one environment",
		PathParams:  []string{"owner", "repo", "name"},
		QueryParams: []string{"environment", "environment[contains]", "environment[in]", "environment[ne]", "limit", "name", "name[contains]", "name[in]", "name[ne]", "order", "page", "q", "repo_id", "repo_id[gt]", "repo_id[gte]", "repo_id[in]", "repo_id[lt]", "repo_id[lte]", "repo_id[ne]", "sort_by"},
		Columns:     []string{"environment", "name", "repo_id", "scoped"},
		IsList:      true,
	},
	{
		Name:        "repo-environments",
		OperationID: "listRepoEnvironments",
		Method:      "GET",
		Path:        "/repos/{owner}/{repo}/environments",
		Summary:     "List one repository's environments",
		PathParams:  []string{"owner", "repo"},
		QueryParams: []string{"approval_policy", "approval_policy[contains]", "approval_policy[in]", "approval_policy[ne]", "created_unix", "created_unix[gt]", "created_unix[gte]", "created_unix[in]", "created_unix[lt]", "created_unix[lte]", "created_unix[ne]", "id", "id[gt]", "id[gte]", "id[in]", "id[lt]", "id[lte]", "id[ne]", "limit", "name", "name[contains]", "name[in]", "name[ne]", "order", "page", "q", "repo_id", "repo_id[gt]", "repo_id[gte]", "repo_id[in]", "repo_id[lt]", "repo_id[lte]", "repo_id[ne]", "required_approvals", "required_approvals[gt]", "required_approvals[gte]", "required_approvals[in]", "required_approvals[lt]", "required_approvals[lte]", "required_approvals[ne]", "sort_by", "sort_order", "sort_order[gt]", "sort_order[gte]", "sort_order[in]", "sort_order[lt]", "sort_order[lte]", "sort_order[ne]", "updated_unix", "updated_unix[gt]", "updated_unix[gte]", "updated_unix[in]", "updated_unix[lt]", "updated_unix[lte]", "updated_unix[ne]"},
		Columns:     []string{"approval_policy", "id", "name", "repo_id", "required_approvals", "sort_order"},
		IsList:      true,
	},
	{
		Name:        "repos",
		OperationID: "listRepos",
		Method:      "GET",
		Path:        "/repos",
		Summary:     "List the repositories the caller can see delivery data for",
		PathParams:  nil,
		QueryParams: []string{"id", "id[gt]", "id[gte]", "id[in]", "id[lt]", "id[lte]", "id[ne]", "is_archived", "is_archived[ne]", "limit", "name", "name[contains]", "name[in]", "name[ne]", "order", "owner_name", "owner_name[contains]", "owner_name[in]", "owner_name[ne]", "page", "q", "sort_by"},
		Columns:     []string{"full_name", "id", "name", "owner"},
		IsList:      true,
	},
}
