// Copyright 2026 The Gitea Authors. All rights reserved.
// SPDX-License-Identifier: MIT

// Package cligen renders a hub CLI's request layer from its area's own operation set, which
// is also what the published OpenAPI document is generated from. The CLI therefore builds
// against the contract rather than a hand-written copy of it, and every endpoint has a
// command by construction.
package cligen

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"
	"unicode"

	hubapi "gitea.dev/routers/api/hub"
)

// CommandName derives a command name from an operation id: the leading verb is dropped and
// the rest is kebab-cased, so listRepoEnvironments becomes repo-environments.
func CommandName(operationID string) string {
	name := operationID
	for _, verb := range []string{"list", "get", "create", "update", "delete"} {
		if strings.HasPrefix(name, verb) && len(name) > len(verb) && unicode.IsUpper(rune(name[len(verb)])) {
			name = name[len(verb):]
			break
		}
	}
	var out []rune
	for i, r := range name {
		if unicode.IsUpper(r) {
			if i > 0 {
				out = append(out, '-')
			}
			r = unicode.ToLower(r)
		}
		out = append(out, r)
	}
	return string(out)
}

// CommandNamesFor lists the commands one operation serves. An operation may declare more
// than one: deploy and rollback compose the identical request and differ only in the release
// tag, so they are one endpoint reached by two names rather than two endpoints.
func CommandNamesFor(op *hubapi.Operation) []string {
	if len(op.CLINames) > 0 {
		return op.CLINames
	}
	return []string{CommandName(op.ID)}
}

// CommandNames lists every command, sorted.
func CommandNames(ops []*hubapi.Operation) []string {
	names := make([]string, 0, len(ops))
	for _, op := range ops {
		names = append(names, CommandNamesFor(op)...)
	}
	sort.Strings(names)
	return names
}

// command is one emitted entry: an operation under one of the names it serves.
type command struct {
	Name string
	Op   *hubapi.Operation
}

// RenderClient emits a binary's generated_client.go, declared under packageName — "main" for a
// binary that serves Commands directly, or an importable package name when a binary re-exports
// it for another caller, such as an integration test, to build against. schemas is the area's
// own published component schemas, which is where the human-readable table's default columns
// come from.
func RenderClient(ops []*hubapi.Operation, schemas map[string]map[string]any, packageName string) ([]byte, error) {
	sorted := make([]command, 0, len(ops))
	seen := map[string]string{}
	for _, op := range ops {
		for _, name := range CommandNamesFor(op) {
			if prev, dup := seen[name]; dup {
				return nil, fmt.Errorf("operations %q and %q both map to command %q; rename one operation id", prev, op.ID, name)
			}
			seen[name] = op.ID
			sorted = append(sorted, command{Name: name, Op: op})
		}
	}
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })
	if packageName == "" {
		packageName = "main"
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, `// Copyright 2026 The Gitea Authors. All rights reserved.
// SPDX-License-Identifier: MIT

// Code generated by tools/hub-generate.go. DO NOT EDIT.
//
// The request layer is generated from the API's operation set, the same set the published
// OpenAPI document is generated from, so a call that no longer matches the contract fails
// the build rather than at runtime.

package %s

import "gitea.dev/cmd/hubcli"

// Commands is every command the CLI serves, one per documented endpoint.
var Commands = []hubcli.Command{
`, packageName)
	for _, c := range sorted {
		op := c.Op
		fmt.Fprintf(&b, "\t{\n")
		fmt.Fprintf(&b, "\t\tName:        %q,\n", c.Name)
		fmt.Fprintf(&b, "\t\tOperationID: %q,\n", op.ID)
		fmt.Fprintf(&b, "\t\tMethod:      %q,\n", op.Method)
		fmt.Fprintf(&b, "\t\tPath:        %q,\n", op.Path)
		fmt.Fprintf(&b, "\t\tSummary:     %q,\n", op.Summary)
		fmt.Fprintf(&b, "\t\tPathParams:  %s,\n", stringSlice(pathParamNames(op)))
		fmt.Fprintf(&b, "\t\tQueryParams: %s,\n", stringSlice(queryParamNames(op)))
		fmt.Fprintf(&b, "\t\tBodyParams:  %s,\n", stringSlice(bodyParamNames(op)))
		fmt.Fprintf(&b, "\t\tRequiredBody: %s,\n", stringSlice(requiredBodyNames(op)))
		fmt.Fprintf(&b, "\t\tBoolBody:    %s,\n", stringSlice(boolBodyNames(op)))
		fmt.Fprintf(&b, "\t\tIntBody:     %s,\n", stringSlice(intBodyNames(op)))
		fmt.Fprintf(&b, "\t\tArrayBody:   %s,\n", stringSlice(arrayBodyNames(op)))
		fmt.Fprintf(&b, "\t\tBodyHelp:    %s,\n", stringMap(bodyHelp(op)))
		fmt.Fprintf(&b, "\t\tColumns:     %s,\n", stringSlice(columnsFor(op, schemas)))
		fmt.Fprintf(&b, "\t\tIsList:      %t,\n", op.ResponseIs == "array")
		fmt.Fprintf(&b, "\t},\n")
	}
	b.WriteString("}\n")

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated client: %w", err)
	}
	return formatted, nil
}

func pathParamNames(op *hubapi.Operation) []string {
	names := make([]string, 0, len(op.PathParams))
	for _, p := range op.PathParams {
		names = append(names, p.Name)
	}
	return names
}

// bodyParamNames lists an operation's request-body members. Each becomes a flag, so a body
// the document publishes always has a way to send it from the CLI.
func bodyParamNames(op *hubapi.Operation) []string {
	names := make([]string, 0, len(op.Body))
	for _, p := range op.Body {
		names = append(names, p.Name)
	}
	sort.Strings(names)
	return names
}

// requiredBodyNames lists the members the endpoint will refuse the request without, so the
// CLI can say so before spending a round-trip.
func requiredBodyNames(op *hubapi.Operation) []string {
	names := make([]string, 0, len(op.Body))
	for _, p := range op.Body {
		if p.Required {
			names = append(names, p.Name)
		}
	}
	sort.Strings(names)
	return names
}

// boolBodyNames lists the members that marshal as JSON booleans rather than strings; the
// flag for one is a switch.
func boolBodyNames(op *hubapi.Operation) []string {
	names := make([]string, 0, len(op.Body))
	for _, p := range op.Body {
		if p.Type == "boolean" {
			names = append(names, p.Name)
		}
	}
	sort.Strings(names)
	return names
}

// intBodyNames lists the members that marshal as JSON numbers rather than strings.
func intBodyNames(op *hubapi.Operation) []string {
	names := make([]string, 0, len(op.Body))
	for _, p := range op.Body {
		if p.Type == "integer" {
			names = append(names, p.Name)
		}
	}
	sort.Strings(names)
	return names
}

// arrayBodyNames lists the members that marshal as JSON arrays rather than strings; the flag
// for one takes a JSON array or a comma-separated list.
func arrayBodyNames(op *hubapi.Operation) []string {
	names := make([]string, 0, len(op.Body))
	for _, p := range op.Body {
		if p.Type == "array" {
			names = append(names, p.Name)
		}
	}
	sort.Strings(names)
	return names
}

// queryParamNames lists every flag a query parameter gets: the grammar's own filterable
// fields plus an operation's non-grammar QueryParams (e.g. getProjectViews' repo), deduplicated
// since a name could in principle appear in both.
func queryParamNames(op *hubapi.Operation) []string {
	seen := map[string]bool{}
	names := make([]string, 0, len(op.QueryParams))
	for _, p := range op.QueryParams {
		if !seen[p.Name] {
			seen[p.Name] = true
			names = append(names, p.Name)
		}
	}
	for _, p := range op.GrammarParams() {
		if !seen[p.Name] {
			seen[p.Name] = true
			names = append(names, p.Name)
		}
	}
	sort.Strings(names)
	return names
}

// columnsFor names the response fields the human-readable table renders. The table is never
// the only output: --json emits the API response verbatim.
func columnsFor(op *hubapi.Operation, schemas map[string]map[string]any) []string {
	schema, ok := schemas[op.Response]
	if !ok {
		return nil
	}
	required, _ := schema["required"].([]string)
	cols := append([]string(nil), required...)
	sort.Strings(cols)
	return cols
}

// bodyHelp carries each body member's published description into the flag's help text, so
// the generated command reference explains the request body rather than merely listing it.
func bodyHelp(op *hubapi.Operation) map[string]string {
	out := make(map[string]string, len(op.Body))
	for _, p := range op.Body {
		if p.Description != "" {
			out[p.Name] = p.Description
		}
	}
	return out
}

func stringMap(values map[string]string) string {
	if len(values) == 0 {
		return "nil"
	}
	keys := make([]string, 0, len(values))
	for k := range values {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	pairs := make([]string, 0, len(keys))
	for _, k := range keys {
		pairs = append(pairs, fmt.Sprintf("%q: %q", k, values[k]))
	}
	return "map[string]string{" + strings.Join(pairs, ", ") + "}"
}

func stringSlice(values []string) string {
	if len(values) == 0 {
		return "nil"
	}
	quoted := make([]string, len(values))
	for i, v := range values {
		quoted[i] = fmt.Sprintf("%q", v)
	}
	return "[]string{" + strings.Join(quoted, ", ") + "}"
}
