// Copyright 2026 The Gitea Authors. All rights reserved.
// SPDX-License-Identifier: MIT

// Package cligen renders the gitea-delivery CLI's request layer from the API's own
// operation set, which is also what the published OpenAPI document is generated from. The
// CLI therefore builds against the contract rather than a hand-written copy of it (K2), and
// every endpoint has a command by construction (K7).
package cligen

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"
	"unicode"

	deliveryv1 "gitea.dev/routers/api/delivery/v1"
)

// CommandName derives a command name from an operation id: the leading verb is dropped and
// the rest is kebab-cased, so listRepoEnvironments becomes repo-environments.
func CommandName(operationID string) string {
	name := operationID
	for _, verb := range []string{"list", "get", "create", "update", "delete"} {
		if strings.HasPrefix(name, verb) && len(name) > len(verb) && unicode.IsUpper(rune(name[len(verb)])) {
			name = name[len(verb):]
			break
		}
	}
	var out []rune
	for i, r := range name {
		if unicode.IsUpper(r) {
			if i > 0 {
				out = append(out, '-')
			}
			r = unicode.ToLower(r)
		}
		out = append(out, r)
	}
	return string(out)
}

// CommandNames lists every command, sorted.
func CommandNames(ops []*deliveryv1.Operation) []string {
	names := make([]string, 0, len(ops))
	for _, op := range ops {
		names = append(names, CommandName(op.ID))
	}
	sort.Strings(names)
	return names
}

// RenderClient emits cmd/gitea-delivery/generated_client.go.
func RenderClient(ops []*deliveryv1.Operation) ([]byte, error) {
	sorted := make([]*deliveryv1.Operation, len(ops))
	copy(sorted, ops)
	sort.Slice(sorted, func(i, j int) bool { return CommandName(sorted[i].ID) < CommandName(sorted[j].ID) })

	seen := map[string]string{}
	for _, op := range sorted {
		name := CommandName(op.ID)
		if prev, dup := seen[name]; dup {
			return nil, fmt.Errorf("operations %q and %q both map to command %q; rename one operation id", prev, op.ID, name)
		}
		seen[name] = op.ID
	}

	var b bytes.Buffer
	b.WriteString(`// Copyright 2026 The Gitea Authors. All rights reserved.
// SPDX-License-Identifier: MIT

// Code generated by tools/delivery-generate.go. DO NOT EDIT.
//
// The request layer is generated from the API's operation set, the same set the published
// OpenAPI document is generated from, so a call that no longer matches the contract fails
// the build rather than at runtime (K2).

package main

// Commands is every command the CLI serves, one per documented endpoint (K3, K7).
var Commands = []Command{
`)
	for _, op := range sorted {
		fmt.Fprintf(&b, "\t{\n")
		fmt.Fprintf(&b, "\t\tName:        %q,\n", CommandName(op.ID))
		fmt.Fprintf(&b, "\t\tOperationID: %q,\n", op.ID)
		fmt.Fprintf(&b, "\t\tMethod:      %q,\n", op.Method)
		fmt.Fprintf(&b, "\t\tPath:        %q,\n", op.Path)
		fmt.Fprintf(&b, "\t\tSummary:     %q,\n", op.Summary)
		fmt.Fprintf(&b, "\t\tPathParams:  %s,\n", stringSlice(pathParamNames(op)))
		fmt.Fprintf(&b, "\t\tQueryParams: %s,\n", stringSlice(queryParamNames(op)))
		fmt.Fprintf(&b, "\t\tColumns:     %s,\n", stringSlice(columnsFor(op)))
		fmt.Fprintf(&b, "\t\tIsList:      %t,\n", op.ResponseIs == "array")
		fmt.Fprintf(&b, "\t},\n")
	}
	b.WriteString("}\n")

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated client: %w", err)
	}
	return formatted, nil
}

func pathParamNames(op *deliveryv1.Operation) []string {
	names := make([]string, 0, len(op.PathParams))
	for _, p := range op.PathParams {
		names = append(names, p.Name)
	}
	return names
}

func queryParamNames(op *deliveryv1.Operation) []string {
	params := op.GrammarParams()
	names := make([]string, 0, len(params))
	for _, p := range params {
		names = append(names, p.Name)
	}
	sort.Strings(names)
	return names
}

// columnsFor names the response fields the human-readable table renders. The table is never
// the only output: --json emits the API response verbatim (K5).
func columnsFor(op *deliveryv1.Operation) []string {
	schema, ok := deliveryv1.Schemas()[op.Response]
	if !ok {
		return nil
	}
	required, _ := schema["required"].([]string)
	cols := append([]string(nil), required...)
	sort.Strings(cols)
	return cols
}

func stringSlice(values []string) string {
	if len(values) == 0 {
		return "nil"
	}
	quoted := make([]string, len(values))
	for i, v := range values {
		quoted[i] = fmt.Sprintf("%q", v)
	}
	return "[]string{" + strings.Join(quoted, ", ") + "}"
}
