// Copyright 2026 The Gitea Authors. All rights reserved.
// SPDX-License-Identifier: MIT

//go:build ignore

// delivery-generate writes every generated delivery artifact:
//
//	docs/delivery/openapi.json      the published OpenAPI 3 contract
//	docs/delivery/cli-reference.md  the CLI command reference, from its own --help
//	cmd/gitea-delivery/generated_client.go  the CLI's request layer, from the document
//
// CI runs it and then gates on `git diff --exit-code`: a CI that merely runs a generator
// proves nothing about what is committed.
//
// Usage:
//
//	go run ./tools/delivery-generate.go          write the artifacts
//	go run ./tools/delivery-generate.go -check   write to a scratch dir and diff
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	deliveryv1 "gitea.dev/routers/api/delivery/v1"
	"gitea.dev/services/delivery/cligen"
)

func main() {
	check := flag.Bool("check", false, "regenerate into a scratch location and diff instead of writing")
	flag.Parse()

	doc, err := deliveryv1.OpenAPI()
	must(err)

	client, err := cligen.RenderClient(deliveryv1.Operations())
	must(err)

	// The command reference is rendered by running the CLI, so the generated request layer
	// has to be on disk before it can be produced.
	staged := map[string][]byte{
		"docs/delivery/openapi.json":             doc,
		"cmd/gitea-delivery/generated_client.go": client,
	}
	failed := false
	for _, path := range sortedKeys(staged) {
		if *check {
			failed = compare(path, staged[path]) || failed
			continue
		}
		write(path, staged[path])
	}

	reference, err := renderCommandReference()
	must(err)
	const referencePath = "docs/delivery/cli-reference.md"
	if *check {
		failed = compare(referencePath, reference) || failed
	} else {
		write(referencePath, reference)
	}

	if failed {
		os.Exit(1)
	}
}

func sortedKeys(m map[string][]byte) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// compare reports whether the committed artifact differs from what the generator produces.
// CI gates on this, not on the generator merely running.
func compare(path string, content []byte) bool {
	existing, err := os.ReadFile(path)
	if err != nil || !bytes.Equal(existing, content) {
		fmt.Fprintf(os.Stderr, "%s is out of date.\n  Suggested action: run `make delivery-generate` and commit the result.\n", path)
		return true
	}
	return false
}

func write(path string, content []byte) {
	must(os.MkdirAll(filepath.Dir(path), 0o755))
	must(os.WriteFile(path, content, 0o644))
	fmt.Println("wrote", path)
}

// renderCommandReference builds the CLI's own command reference from its --help output, so
// agent-facing documentation is never hand-maintained beside the commands it describes.
func renderCommandReference() ([]byte, error) {
	var out bytes.Buffer
	out.WriteString("<!-- Generated by tools/delivery-generate.go from `gitea-delivery --help`. Do not edit. -->\n")
	out.WriteString("# gitea-delivery command reference\n\n")

	root, err := helpOutput()
	if err != nil {
		return nil, err
	}
	out.WriteString("## gitea-delivery\n\n```\n")
	out.WriteString(root)
	out.WriteString("```\n")

	names := cligen.CommandNames(deliveryv1.Operations())
	for _, name := range names {
		sub, err := helpOutput(name)
		if err != nil {
			return nil, err
		}
		fmt.Fprintf(&out, "\n## gitea-delivery %s\n\n```\n%s```\n", name, sub)
	}
	return out.Bytes(), nil
}

func helpOutput(args ...string) (string, error) {
	cmd := exec.Command("go", append([]string{"run", "./cmd/gitea-delivery"}, append(args, "--help")...)...)
	cmd.Env = append(os.Environ(), "GITEA_DELIVERY_HELP_WIDTH=100")
	raw, err := cmd.CombinedOutput()
	if err != nil {
		return "", fmt.Errorf("gitea-delivery %s --help: %w\n%s", strings.Join(args, " "), err, raw)
	}
	return string(raw), nil
}

func must(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, "delivery-generate:", err)
		os.Exit(1)
	}
}
